version: '3'

services:
  trxmanage:
    environment:
      - NODE_ENV=production
    image: fair/trx-fairgame-manage:latest
    volumes:
      - /home/static:/usr/src/app/public/images
    container_name: trxmanage
    restart: always
    ports:
      - "4000:4000"
    privileged: true

