version: '3'

services:
  manage:
    environment:
      - NODE_ENV=production
    image: fair/fairgame-manage:latest
    volumes:
      - /home/static:/usr/src/app/public/images
    container_name: manage
    restart: always
    ports:
      - "4000:4000"
    privileged: true

